Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list containing string elements ('1', '2', '3', '4', '5'). The data type of elements in list_ is str (string).

The variable array_list is a NumPy array created from the list_ using np.array(). When you create a NumPy array from a list of strings like this, the array will typically have a data type of '<U1', which represents a Unicode string of length 1.

To print the data types of both list_ and array_list, you can use the following code:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_[0]))  # Data type of elements in list_
print("Data type of array_list:", array_list.dtype)  # Data type of elements in array_list


Data type of list_: <class 'str'>
Data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Print data type of each element in list_
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of elements in array_list:")
for element in array_list:
    print(element.dtype)

    
# The output will show the data type of each element in both list_ and array_list. 
# The elements in list_ are all strings (str), while the elements in array_list are represented as Unicode strings (<U1).

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:
    
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Yes, there will be a difference in the data types of the elements present in list_ and array_list when you create array_list with the specified dtype as int.

Let's examine the data types of each element in list_ and array_list after making this change:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Print data type of each element in list_
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In this modified code:

np.array(list_, dtype=int) creates array_list from list_, converting each element to an integer (int).
We iterate over list_ and array_list to print the data type of each element.
Now, let's analyze the output:

For list_ (original list of strings):

The data type of each element in list_ remains str (string), as they are not converted during the creation of array_list.
For array_list (NumPy array with dtype=int):

Each element in array_list will be of type numpy.int64 (assuming default integer type on your system), as specified by the dtype=int argument during array creation.
Therefore, after the change, list_ contains string elements ('1', '2', '3', '4', '5'), while array_list contains integer elements (1, 2, 3, 4, 5).

The above code will print the data types accordingly for each element in both list_ and array_list.

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Finding the shape of num_array
shape_of_array = num_array.shape
print("Shape of num_array:", shape_of_array)

# (ii) Finding the size of num_array
size_of_array = num_array.size
print("Size of num_array:", size_of_array)


Shape of num_array: (2, 3)
Size of num_array: 6


Explanation:

np.array(num_list) creates a NumPy array num_array from the nested list num_list.
num_array.shape returns a tuple representing the shape of the array, where the first value is the number of rows and the second value is the number of columns (if it's a 2D array). For example, if num_array is a 2D array with 2 rows and 3 columns, shape_of_array will be (2, 3).
num_array.size returns the total number of elements in the array. For a 2D array like num_array (with shape (2, 3) in this case), size_of_array will be 6 (2 rows × 3 columns).

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

# Create a 3x3 array filled with zeros
zero_matrix = np.zeros((3, 3))

# Print the created array
print("Array of zeros (3x3):")
print(zero_matrix)


Array of zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [8]:
import numpy.matlib as nm
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])